import type { ClusterSpec, ModelSpec, ParallelConfig } from "./types";

export const modelTemplates: ModelSpec[] = [
  {
    id: "deepseek-v3",
    name: "DeepSeek-V3 MoE 训练模板",
    totalParamsB: 671,
    activeParamsB: 37,
    layers: 61,
    hiddenSize: 7168,
    attentionHeads: 128,
    sequenceLength: 4096,
    vocabSize: 129_280,
    expertCount: 256,
    routedExperts: 256,
    sharedExperts: 1,
    topK: 8,
    moeLayerFrequency: 58 / 61,
    capacityFactor: 1.25,
    tokenImbalanceFactor: 1.08,
  },
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek-V4-Pro 类 MoE 模板",
    totalParamsB: 1600,
    activeParamsB: 49,
    layers: 96,
    hiddenSize: 7168,
    attentionHeads: 128,
    sequenceLength: 1_000_000,
    vocabSize: 129_280,
    expertCount: 384,
    routedExperts: 384,
    sharedExperts: 1,
    topK: 8,
    moeLayerFrequency: 1,
    capacityFactor: 1.25,
    tokenImbalanceFactor: 1.12,
  },
  {
    id: "dense-70b",
    name: "Dense 70B 基线",
    totalParamsB: 70,
    activeParamsB: 70,
    layers: 80,
    hiddenSize: 8192,
    attentionHeads: 64,
    sequenceLength: 4096,
    vocabSize: 128_000,
    expertCount: 0,
    routedExperts: 0,
    sharedExperts: 0,
    topK: 0,
    moeLayerFrequency: 0,
    capacityFactor: 1,
    tokenImbalanceFactor: 1,
  },
];

export const clusterTemplates: ClusterSpec[] = [
  {
    name: "H100 512-GPU IB 集群",
    nodes: 64,
    gpusPerNode: 8,
    gpuMemoryGB: 80,
    bf16Tflops: 989,
    hbmBandwidthGBps: 3350,
    intraNodeBandwidthGBps: 900,
    interNodeBandwidthGBps: 100,
    networkLatencyUs: 3.5,
  },
  {
    name: "Ascend 类 64-GPU 集群",
    nodes: 8,
    gpusPerNode: 8,
    gpuMemoryGB: 64,
    bf16Tflops: 376,
    hbmBandwidthGBps: 1800,
    intraNodeBandwidthGBps: 392,
    interNodeBandwidthGBps: 50,
    networkLatencyUs: 5,
  },
];

export const defaultParallelConfig: ParallelConfig = {
  dp: 4,
  tp: 4,
  pp: 4,
  ep: 8,
  microBatchSize: 1,
  globalBatchSize: 512,
  gradientAccumulationSteps: 16,
  zeroStage: 2,
  fsdp: true,
  activationCheckpointing: true,
  overlapEfficiency: 0.62,
  computeEfficiency: 0.42,
};
